echo -ne "FOO"
echo -ne "\x1b\x5b""C"
echo -ne "BAR"
echo ""
echo -ne "FOO"
echo -ne "\x1b\x5b""0C"
echo -ne "BAR"
echo ""
echo -ne "FOO"
echo -ne "\x1b\x5b""1C"
echo -ne "BAR"
echo ""
echo -ne "FOO"
echo -ne "\x1b\x5b""2C"
echo -ne "BAR"
echo ""
echo -ne "FOO"
echo -ne "\x1b\x5b""3C"
echo -ne "BAR"
echo ""

