echo -ne "+FOOBARBAZ"
echo -ne "\x1b\x5b""10D"
echo -ne "ZZZZZZZZZZ"
echo ""
echo -ne "++FOOBARBAZ"
echo -ne "\x1b\x5b""10D"
echo -ne "ZZZZZZZZZZ"
echo ""
echo -ne "FOOBARBAZ"
echo -ne "\x1b\x5b""10D"
echo -ne "ZZZZZZZZZZ"
echo ""
