echo -ne "+FOOBARBAZ"
echo -ne "\x1b\x5b""10D"
echo -ne "XXXXXXXXXX"
echo ""
echo -ne "++FOOBARBAZ"
echo -ne "\x1b\x5b""10D"
echo -ne "XXXXXXXXXX"
echo ""
echo -ne "FOOBARBAZ"
echo -ne "\x1b\x5b""10D"
echo -ne "XXXXXXXXXX"
echo ""
echo -ne "FOOBARBAZ"
echo -ne "\x1b\x5b""0D"
echo -ne "XXXXXXXXXX"
echo ""
